version: "3"

services:
  code-editor:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: code-editor
    ports:
      - "5000:5000"
      - "3000:3000"
      - "8000:8000"

    volumes:
      - .:/app
      - /app/node_modules

    stdin_open: true
    tty: true

    